
#-----------XGBoost_selected_configuration

XGBOOST = "xgboost"
MODEL_TYPE = XGBOOST
VERSION_MODEL = "1.0.0"
XGB_SELECTED_LEARNING_RATE = 0.03
XGB_SELECTED_N_ESTIMATORS = 700
XGB_SELECTED_MAX_DEPTH = 9
XGB_SELECTED_SUBSAMPLE = 0.6
XGB_SELECTED_COLSAMPLE = 0.9
XGB_SELECTION_METRIC = "macro_f1"
XGB_CV_MACRO_F1 = 0.8268
XGB_TEST_MACRO_F1 = 0.8227

PREPROCESSOR_OUTPUT_PATH_SELECTED = f"models/selected/preprocessor_{MODEL_TYPE}_{VERSION_MODEL}.joblib"
MODEL_OUTPUT_PATH_SELECTED = f"models/selected/model_{MODEL_TYPE}_{VERSION_MODEL}.joblib"
LABEL_ENCODER_OUTPUT_PATH_SELECTED = f"models/selected/label_encoding_{MODEL_TYPE}_{VERSION_MODEL}.joblib"
METADATA_PATH_SELECTED = f"models/selected/metadata_{MODEL_TYPE}_{VERSION_MODEL}.json"